# Generated by Django 5.2.7 on 2025-12-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('energetic', 'Energetic'), ('calm', 'Calm'), ('romantic', 'Romantic')], max_length=20)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs/')),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
            ],
        ),
    ]
